export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const AUTH_USER = 'AUHT_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const READ_BOOKS_SUCCESS = 'READ_BOOKS_SUCCESS';
export const READ_BOOK_SUCCES = 'READ_BOOK_SUCCES';
export const READ_BOOK_FAILURE = 'READ_BOOK_FAILURE';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const CREATE_BOOK_FAILURE = 'CREATE_BOOK_FAILURE';
